spring:
  cloud:
    stream:
      bindings:
        subscriptionOnMoneyTransferredChannel:
          destination: "moneyTransferredExchange"
  rabbitmq:
    host: "rabbitmq"
  h2:
    console:
      enabled: true
      path: "/h2-console"
  datasource:
    url: "jdbc:h2:~/test"
    username: "sa"
    password: ""
server:
  port: 8080